openapi: 3.0.1
info:
  title: Kosovo-Serbia Media & Public Opinion API
  version: "1.0.0"
  description: |
    Hírek és közösségi médiás tartalmak gyűjtése, elemzése Koszovó és Szerbia témakörében,
    geo-fókusz, érzelmi tónus, források hitelessége, és diskurzusminták alapján.

servers:
  - url: https://e654-193-176-126-42.ngrok-free.app -> http://localhost:8000 

paths:
  /searchNews:
    post:
      summary: Többforrású hírkeresés, összefoglalás, eseménycímkézés és hitelesség-ellenőrzés
      operationId: searchNews
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/NewsSearchRequest"
      responses:
        "200":
          description: Strukturált hírelemzés
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/NewsSearchResponse"

  /getTrendingSocialMedia:
    post:
      summary: Közösségi média trendek és diskurzusértelmezés (érzelmi tónus, narratívák, kampányok)
      operationId: getTrendingSocialMedia
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/SocialMediaRequest"
      responses:
        "200":
          description: Értelmezett közösségi média diskurzus elemzés
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/SocialMediaResponse"

components:
  schemas:

    NewsSearchRequest:
      type: object
      required: [from_date, to_date]
      properties:
        from_date:
          type: string
          format: date
          description: "Kezdődátum (pl. 2025-05-01)"
        to_date:
          type: string
          format: date
          description: "Végdátum (pl. 2025-05-07)"
        keywords:
          type: array
          items:
            type: string
          description: "Kulcsszavak vagy témák (pl. 'EU-integráció', 'Választások')"
        language:
          type: string
          enum: [sq, sr, en]
          description: "Hírek nyelve: albán, szerb vagy angol"

    NewsSearchResponse:
      type: object
      properties:
        articles:
          type: array
          items:
            type: object
            properties:
              title:
                type: string
              date:
                type: string
                format: date
              summary:
                type: string
              source:
                type: object
                properties:
                  name:
                    type: string
                  url:
                    type: string
                  bias:
                    type: string
                    enum: [semleges, kormányközeli, ellenzéki, nemzetközi, regionális, szerbiai állami]
              tags:
                type: array
                items:
                  type: string
              keywords:
                type: array
                items:
                  type: string
              location:
                type: string
                description: "Földrajzi fókusz (pl. Észak-Koszovó, Belgrád)"
              credibility_check:
                type: string
                description: "Hitelességi megjegyzés, pl. 'több forrás megerősítette / cáfolta'"

    SocialMediaRequest:
      type: object
      required: [from_date, to_date, platforms]
      properties:
        from_date:
          type: string
          format: date
        to_date:
          type: string
          format: date
        platforms:
          type: array
          items:
            type: string
            enum: [facebook, instagram, x, tiktok]
        keywords:
          type: array
          items:
            type: string
          description: "Kulcsszavak, hashtagek, szereplők (pl. #Vucic, #Kurti)"

    SocialMediaResponse:
      type: object
      properties:
        platforms:
          type: array
          items:
            type: object
            properties:
              name:
                type: string
              top_posts:
                type: array
                items:
                  type: object
                  properties:
                    content:
                      type: string
                    reach:
                      type: integer
                    reactions:
                      type: object
                      additionalProperties:
                        type: integer
                    author_type:
                      type: string
                      enum: [hivatalos, civil, híroldal, magánszemély]
              tone_analysis:
                type: object
                properties:
                  positive_examples:
                    type: array
                    items:
                      type: string
                  negative_examples:
                    type: array
                    items:
                      type: string
                  neutral_examples:
                    type: array
                    items:
                      type: string
              narratives:
                type: array
                items:
                  type: string
              manipulation_signs:
                type: array
                items:
                  type: string
                description: "Pl. botminta, koordinált kampány, automatizált tartalom"