openapi: 3.1.0
info:
  title: Kosovo Media Monitor API
  description: >
    Koszovói médiamonitorozó és közösségi médiaelemző asszisztens API-specifikáció.
    Lehetővé teszi hírek lekérdezését, közösségi médiaelemzést, szentimentelemzést és bottevékenység vizsgálatát.
  version: 1.0.0
servers:
  - url: https://api.kosovo-media-monitor.ai
    description: Production server

paths:

  /news/search:
    get:
      operationId: searchNews
      summary: Hírek keresése koszovói és szerbiai hírportálokon.
      description: Lekéri a híreket a megadott hírportálokról időintervallum és kulcsszavak alapján.
      parameters:
        - name: from
          in: query
          required: true
          description: A keresés kezdő dátuma (YYYY-MM-DD).
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          description: A keresés vége dátuma (YYYY-MM-DD).
          schema:
            type: string
            format: date
        - name: keywords
          in: query
          required: false
          description: Kulcsszavak a kereséshez, vesszővel elválasztva.
          schema:
            type: string
        - name: sources
          in: query
          required: false
          description: Hírforrások, vesszővel elválasztva (pl. Koha Ditore, Gazeta Express).
          schema:
            type: string
      responses:
        '200':
          description: Talált hírek listája.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    title:
                      type: string
                    url:
                      type: string
                    publishedAt:
                      type: string
                      format: date-time
                    summary:
                      type: string
                    source:
                      type: string

  /socialmedia/trending:
    get:
      operationId: getTrendingSocialMedia
      summary: Népszerű közösségi médiás tartalmak lekérdezése.
      description: Visszaadja a legnépszerűbb posztokat a megadott platformról adott időintervallumban.
      parameters:
        - name: platform
          in: query
          required: true
          description: A közösségi média platform neve.
          schema:
            type: string
            enum: [facebook, instagram, x, tiktok, telegram, snapchat]
        - name: from
          in: query
          required: true
          description: Időintervallum kezdete (YYYY-MM-DD).
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          description: Időintervallum vége (YYYY-MM-DD).
          schema:
            type: string
            format: date
      responses:
        '200':
          description: A közösségi médiás trendek listája.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    platform:
                      type: string
                    postUrl:
                      type: string
                    content:
                      type: string
                    engagement:
                      type: object
                      properties:
                        likes:
                          type: integer
                        shares:
                          type: integer
                        comments:
                          type: integer
                    sentiment:
                      type: string
                      enum: [positive, neutral, negative]
                    authorType:
                      type: string
                      enum: [official, influencer, anonymous, media]

  /text/analyze:
    post:
      operationId: analyzeText
      summary: Szöveg szentiment- és narratívaelemzése.
      description: Elemezi a megadott szöveg érzelmi tónusát, kulcsszavait és domináns narratíváit.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: Az elemzendő szöveg.
                language:
                  type: string
                  description: A szöveg nyelve (pl. sq, sr, en).
                  example: "sq"
      responses:
        '200':
          description: Elemzési eredmények.
          content:
            application/json:
              schema:
                type: object
                properties:
                  sentiment:
                    type: string
                    enum: [positive, neutral, negative]
                  keywords:
                    type: array
                    items:
                      type: string
                  narrativeClusters:
                    type: array
                    items:
                      type: string

  /socialmedia/botcheck:
    post:
      operationId: checkBotActivity
      summary: Bot-aktivitás ellenőrzése közösségi médiás fiókokon.
      description: Elemzi, hogy az adott felhasználók botként viselkednek-e.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                usernames:
                  type: array
                  items:
                    type: string
                  description: A vizsgált közösségi médiás felhasználónevek listája.
      responses:
        '200':
          description: Bot-aktivitási valószínűségek.
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    username:
                      type: string
                    botProbability:
                      type: number
                      description: 0 és 1 közötti valószínűségi érték.

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

security:
  - apiKeyAuth: []
