openapi: 3.1.0
info:
  title: Kosovo-Serbia Advanced Media Analysis API
  description: >
    Fejlett médiamonitorozó és közösségi médiaelemző API, amely Koszovó és Szerbia tekintetében nyújt részletes, strukturált elemzést valós időben, integrált botdetektálással és hitelességi ellenőrzéssel.
  version: 2.0.0
servers:
  - url: https://api.kosovo-media-monitor.ai/v2
    description: Production server

paths:
  /news/search:
    get:
      tags:
        - News
      summary: Hírek részletes keresése
      operationId: getNewsSearch
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: keywords
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true
        - name: sources
          in: query
          required: false
          schema:
            type: array
            items:
              type: string
            style: form
            explode: true
      responses:
        "200":
          description: Részletes hírek strukturált listája
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/NewsItem"
              examples:
                exampleNews:
                  value:
                    - title: "Szerbia új médiatörvényt fogadott el"
                      url: "https://example.com/news"
                      publishedAt: "2025-05-20"
                      summary: "A törvény célja a dezinformáció elleni küzdelem."
                      source:
                        name: "RTS"
                        orientation: "serbian-state"
                      eventTags: ["law", "media"]
                      keywords: ["media", "law", "serbia"]
                      credibilityScore: 78.5
        "400":
          description: Hibás kérés – hiányzó vagy hibás paraméter
        "401":
          description: Nincs jogosultság – érvénytelen API kulcs

  /socialmedia/trending:
    get:
      tags:
        - Social Media
      summary: Közösségi média trendek elemzése
      operationId: getSocialMediaTrending
      parameters:
        - name: platform
          in: query
          required: true
          schema:
            type: string
            enum:
              - facebook
              - instagram
              - x
              - tiktok
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Strukturált közösségi média trendek
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/SocialMediaTrend"
        "400":
          description: Hibás kérés
        "401":
          description: Jogosulatlan hozzáférés

  /news/fallback:
    get:
      tags:
        - News
      summary: Alternatív gyors hírek lekérése
      operationId: getNewsFallback
      parameters:
        - name: from
          in: query
          required: true
          schema:
            type: string
            format: date
        - name: to
          in: query
          required: true
          schema:
            type: string
            format: date
      responses:
        "200":
          description: Egyszerűsített hírek
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/FallbackNewsItem"
        "400":
          description: Hibás kérés
        "401":
          description: Jogosulatlan hozzáférés

  /geo/detailed-hotspots:
    get:
      tags:
        - Geolocation
      summary: Részletes regionális aktivitáselemzés
      operationId: getGeoHotspots
      parameters:
        - name: region
          in: query
          required: true
          schema:
            type: string
            enum:
              - kosovo
              - serbia
      responses:
        "200":
          description: Részletes regionális eseményadatok
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/GeoHotspot"
        "400":
          description: Hibás kérés
        "401":
          description: Jogosulatlan hozzáférés

security:
  - apiKeyAuth: []

components:
  securitySchemes:
    apiKeyAuth:
      type: apiKey
      in: header
      name: X-API-Key

  schemas:
    NewsItem:
      type: object
      properties:
        title:
          type: string
        url:
          type: string
        publishedAt:
          type: string
          format: date
        summary:
          type: string
        source:
          type: object
          properties:
            name:
              type: string
            orientation:
              type: string
              enum:
                - neutral
                - pro-government
                - opposition
                - international
                - regional
                - serbian-state
        eventTags:
          type: array
          items:
            type: string
        keywords:
          type: array
          items:
            type: string
        credibilityScore:
          type: number
          minimum: 0
          maximum: 100
          example: 78.5

    FallbackNewsItem:
      type: object
      properties:
        title:
          type: string
        url:
          type: string
        publishedAt:
          type: string
          format: date
        source:
          type: string

    SocialMediaTrend:
      type: object
      properties:
        platform:
          type: string
        postUrl:
          type: string
        content:
          type: string
        engagement:
          type: object
          properties:
            likes:
              type: integer
            shares:
              type: integer
            comments:
              type: integer
        topComments:
          type: array
          items:
            type: object
            properties:
              comment:
                type: string
              sentiment:
                type: string
                enum:
                  - positive
                  - negative
                  - neutral
        dominantNarratives:
          type: array
          items:
            type: string
        authorType:
          type: string
          enum:
            - individual
            - influencer
            - media
            - organization
            - bot
        botActivityDetected:
          type: boolean

    GeoHotspot:
      type: object
      properties:
        location:
          type: string
        coordinates:
          type: object
          properties:
            lat:
              type: number
            lon:
              type: number
        postCount:
          type: integer
        dominantTopics:
          type: array
          items:
            type: string
        sentimentDistribution:
          type: object
          properties:
            positive:
              type: integer
            negative:
              type: integer
            neutral:
              type: integer